version: '3.1'
services:
  db:
    image: mysql
    container_name: distprog-procurement
    environment:
      MYSQL_ROOT_PASSWORD: root
      #To map for another port
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - distprog-procurement:/var/lib/mysql

volumes:
  distprog-procurement:
